"""add enrichment_hold to master_leads

Revision ID: 2371a37f36af
Revises: 38fa8609cfc8
Create Date: 2026-07-12 16:21:57.880792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2371a37f36af'
down_revision: Union[str, None] = '38fa8609cfc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_leads', sa.Column('enrichment_hold', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_leads', 'enrichment_hold')
    # ### end Alembic commands ###
