"""add enrichment_attempts

Revision ID: 24917d78c6f4
Revises: 8f5c6bab3031
Create Date: 2026-07-11 06:20:14.275050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '24917d78c6f4'
down_revision: Union[str, None] = '8f5c6bab3031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrichment_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cost_incurred', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['master_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrichment_attempts_cost_mode'), 'enrichment_attempts', ['cost_mode'], unique=False)
    op.create_index(op.f('ix_enrichment_attempts_lead_id'), 'enrichment_attempts', ['lead_id'], unique=False)
    op.create_index(op.f('ix_enrichment_attempts_type'), 'enrichment_attempts', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrichment_attempts_type'), table_name='enrichment_attempts')
    op.drop_index(op.f('ix_enrichment_attempts_lead_id'), table_name='enrichment_attempts')
    op.drop_index(op.f('ix_enrichment_attempts_cost_mode'), table_name='enrichment_attempts')
    op.drop_table('enrichment_attempts')
    # ### end Alembic commands ###
