"""add row_count_with_email to batches

Revision ID: 4c506a803e1f
Revises: a28ec9635c1c
Create Date: 2026-07-11 04:37:49.319511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4c506a803e1f'
down_revision: Union[str, None] = 'a28ec9635c1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default='0' so this doesn't fail against the existing (non-empty)
    # batches table — new rows still get their value from the Python-side
    # Field(default=0), this is only for the ALTER TABLE to succeed.
    op.add_column(
        'batches',
        sa.Column('row_count_with_email', sa.Integer(), nullable=False, server_default='0'),
    )
    # Backfill existing batches with the real count, since 0 would be wrong
    # for the 3 batches uploaded before this column existed.
    op.execute("""
        UPDATE batches b
        SET row_count_with_email = (
            SELECT count(DISTINCT ls.lead_id)
            FROM lead_sources ls
            JOIN master_leads ml ON ml.id = ls.lead_id
            WHERE ls.batch_id = b.id AND ml.email IS NOT NULL
        )
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'row_count_with_email')
    # ### end Alembic commands ###
