"""add exports and export_leads

Revision ID: 8f5c6bab3031
Revises: 4c506a803e1f
Create Date: 2026-07-11 05:51:58.192353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8f5c6bab3031'
down_revision: Union[str, None] = '4c506a803e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('destination', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheduled_month', sa.Date(), nullable=False),
    sa.Column('lead_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exports_destination'), 'exports', ['destination'], unique=False)
    op.create_index(op.f('ix_exports_scheduled_month'), 'exports', ['scheduled_month'], unique=False)
    op.create_table('export_leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('export_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['export_id'], ['exports.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['master_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_leads_export_id'), 'export_leads', ['export_id'], unique=False)
    op.create_index(op.f('ix_export_leads_lead_id'), 'export_leads', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_export_leads_lead_id'), table_name='export_leads')
    op.drop_index(op.f('ix_export_leads_export_id'), table_name='export_leads')
    op.drop_table('export_leads')
    op.drop_index(op.f('ix_exports_scheduled_month'), table_name='exports')
    op.drop_index(op.f('ix_exports_destination'), table_name='exports')
    op.drop_table('exports')
    # ### end Alembic commands ###
