"""initial LMS schema: batches, mapping_functions, raw_rows, master_leads, lead_sources

Revision ID: a28ec9635c1c
Revises: 
Create Date: 2026-07-11 03:44:49.846432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a28ec9635c1c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapping_functions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mapping_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mapping_functions_fingerprint'), 'mapping_functions', ['fingerprint'], unique=True)
    op.create_table('master_leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email_confidence', sa.Float(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('social_youtube', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('social_twitter', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('social_instagram', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('social_tiktok', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('social_facebook', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('social_linkedin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('niche', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_discovered_at', sa.DateTime(), nullable=True),
    sa.Column('youtube_channel_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('youtube_channel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('youtube_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('youtube_subscriber_count', sa.Integer(), nullable=True),
    sa.Column('youtube_video_count', sa.Integer(), nullable=True),
    sa.Column('youtube_uploads_last_30d', sa.Integer(), nullable=True),
    sa.Column('youtube_avg_views', sa.Integer(), nullable=True),
    sa.Column('youtube_last_upload_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_leads_country'), 'master_leads', ['country'], unique=False)
    op.create_index(op.f('ix_master_leads_email'), 'master_leads', ['email'], unique=False)
    op.create_index(op.f('ix_master_leads_youtube_channel_id'), 'master_leads', ['youtube_channel_id'], unique=False)
    op.create_index(op.f('ix_master_leads_youtube_channel_name'), 'master_leads', ['youtube_channel_name'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_sheet_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mapping_function_id', sa.Uuid(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('row_count_raw', sa.Integer(), nullable=False),
    sa.Column('row_count_valid', sa.Integer(), nullable=False),
    sa.Column('row_count_quarantined', sa.Integer(), nullable=False),
    sa.Column('row_count_new_leads', sa.Integer(), nullable=False),
    sa.Column('row_count_merged', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mapping_function_id'], ['mapping_functions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_source'), 'batches', ['source'], unique=False)
    op.create_table('raw_rows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quarantine_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_rows_batch_id'), 'raw_rows', ['batch_id'], unique=False)
    op.create_table('lead_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('row_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['master_leads.id'], ),
    sa.ForeignKeyConstraint(['row_id'], ['raw_rows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_sources_batch_id'), 'lead_sources', ['batch_id'], unique=False)
    op.create_index(op.f('ix_lead_sources_lead_id'), 'lead_sources', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_sources_lead_id'), table_name='lead_sources')
    op.drop_index(op.f('ix_lead_sources_batch_id'), table_name='lead_sources')
    op.drop_table('lead_sources')
    op.drop_index(op.f('ix_raw_rows_batch_id'), table_name='raw_rows')
    op.drop_table('raw_rows')
    op.drop_index(op.f('ix_batches_source'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_master_leads_youtube_channel_name'), table_name='master_leads')
    op.drop_index(op.f('ix_master_leads_youtube_channel_id'), table_name='master_leads')
    op.drop_index(op.f('ix_master_leads_email'), table_name='master_leads')
    op.drop_index(op.f('ix_master_leads_country'), table_name='master_leads')
    op.drop_table('master_leads')
    op.drop_index(op.f('ix_mapping_functions_fingerprint'), table_name='mapping_functions')
    op.drop_table('mapping_functions')
    # ### end Alembic commands ###
