"""add person company columns to master_leads

Revision ID: aea2243dc6a8
Revises: 2371a37f36af
Create Date: 2026-07-20 12:23:49.391508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aea2243dc6a8'
down_revision: Union[str, None] = '2371a37f36af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_leads', sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('master_leads', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('master_leads', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('master_leads', sa.Column('job_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('master_leads', sa.Column('seniority', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('master_leads', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('master_leads', sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('master_leads', sa.Column('company_linkedin', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_leads', 'company_linkedin')
    op.drop_column('master_leads', 'company_name')
    op.drop_column('master_leads', 'phone')
    op.drop_column('master_leads', 'seniority')
    op.drop_column('master_leads', 'job_title')
    op.drop_column('master_leads', 'last_name')
    op.drop_column('master_leads', 'first_name')
    op.drop_column('master_leads', 'industry')
    # ### end Alembic commands ###
